export enum RegisterCompetitionRegion {
    Jawa = "Jawa",
    Sumatera = "Sumatera",
    BaliDanNusaTenggara = "Bali dan Nusa Tenggara",
    Kalimantan = "Kalimantan",
    Sulawesi = "Sulawesi",
    PapuaDanMaluku = "Papua dan Maluku",
    International = "International",
}

export const FinalBenmax = [
    "Actprose",
    "Anak'e Agus",
    "Apeni",
    "BICA",
    "BYMAX",
    "CARDIS ( Cardiac Device Innovation and Study )",
    "E'PROSTHE",
    "FROZEN",
    "Genesha",
    "JEM",
    "Kalmina Team",
    "Kuda Lapar",
    "Mecha",
    "MedMech",
    "NekoVerse",
    "Outdonesia",
    "PROSTECO",
    "TBslayers",
    "Throne",
    "Ziplife",
    "GASKEUN",
    "Noroc",
    "feeRandom",
    "G4R4S1",
    "homework",
    "HEHE",
    "Impulsif Gurl",
    "SIGMANETIC",
    "TRANCYS",
    "medicology"
]